Repository Andrew-Ritchie/Smart-Badge, pull requests merged in 2020-02, with the labels that each got.

#20 Interrupt buttons
  dev/sensors.py
Labels: backend

#25 #19 Generic app designed
  dev/app.py
  dev/main_menu.py
  dev/name.py
  dev/test_main.py
  dev/widgets.py
Labels: backend

#27 #22 Navigable Buttons
  dev/app.py
  dev/main_menu.py
  dev/name.py
  dev/test_main.py
  dev/widgets.py
Labels: frontend

#32 #26 Graphics for games initialised
  dev/.pong.py.swp
  dev/app.py
  dev/debug_pong.py
  dev/game.py
  dev/icons.py
  dev/maze.py
  dev/pong.py
  dev/test.py
  dev/test_game.py
  dev/test_pong.py
  dev/widgets.py
Labels: frontend, games
