Repository Andrew-Ritchie/Smart-Badge, pull requests merged in 2020-03, with the labels that each got.

#48 45 menu for apps
  SmartBadge/high_scores.json
  SmartBadge/lib/screen/icons.py
  SmartBadge/main_menu.py
  SmartBadge/maze.py
  SmartBadge/name.py
  SmartBadge/pong.py
  SmartBadge/settings.py
  SmartBadge/test_main.py
  SmartBadge/test_maze.py
Labels: app

#52 #47 QR Code and setup script
  SmartBadge/lib/app.py
  SmartBadge/lib/ext/sensors.py
  SmartBadge/lib/screen/imagetools.py
  SmartBadge/lib/screen/widgets.py
  SmartBadge/name.py
  SmartBadge/settings.json
  SmartBadge/test_main.py
  SmartBadge/vcard.png
  external/setup.py
Labels: app, backend

#50 #37 accelerometer
  SmartBadge/lib/ext/lis3dh.py
  SmartBadge/lib/ext/sensors.py
Labels: backend
